### ISSUE TITLE
DrawName : rotate probably needs 'expand=1' 

### ISSUE THREAD

**Issue by jjmz** [Henkru/ChipLaber#1]
When running the code with the Z80 data, only 1/3 of the chip is drawn (152 pixels, centered).
If using the '-hide' option, everything is fine.

Seems that the code in DrawName would require 'expand=1' so that the rotated image is large enough. If not it is limited to the width of the original image.

	def drawName(self):
		self.im = self.im.rotate(90, expand=1)
		self.draw = ImageDraw.Draw(self.im)

		nameFont = ImageFont.truetype(self.fontPath, self.nameFontSize)
		textSize = self.draw.textsize(self.name, font=nameFont)

		x = int(self.height/2 - textSize[0]/2)
		y = int(self.width/2 - textSize[1]/2)

		self.draw.text((x, y), self.name, font=nameFont, fill=0)

		self.im = self.im.rotate(-90, expand=1)
		self.draw = ImageDraw.Draw(self.im)

**Comment by Henkru** [comment]
Seems that the default behaviour of Pillow has changed. I added the `expand` argument for the rotate calls.
